controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil: 
    path: /accueil
    controller: App\Controller\HomeController::bonjour

redirecttoroute: 
    path: /redirecttoroute
    controller: App\Controller\HomeController::aurevoir

redirecttogoogle: 
    path: /redirecttogoogle
    controller: App\Controller\HomeController::redirecttogoogle